### ISSUE TITLE
Support for multiple events

### ISSUE THREAD

**Issue by AndreiVidrasco** [ActionKit/ActionKit#10]
In Obj-C, we have possibility to add target, for example 
UIControlEventTouchDown  | UIControlEventTouchUpInside

In Swift, for this option we should use array 
[.TouchUpInside, .TouchDown]

button.addControlEvent([.TouchUpInside, .TouchDown], closure: {})
doesn't show error on compile time, but actions is not added to button

**Comment by coolbnjmn** [comment]
If you would like to submit a PR I'd gladly go over it, but otherwise we probably won't have time to look at this right away. 

Thanks

**Comment by AndreiVidrasco** [comment]
https://github.com/ActionKit/ActionKit/pull/11

**Comment by coolbnjmn** [comment]
Merged, thanks so much for the quick work!
Looks great :)
