### ISSUE TITLE
is only support for iOS 9+ ?

### ISSUE THREAD

**Issue by ChendayUP** [ActionKit/ActionKit#28]
i will support ios 8+

**Comment by coolbnjmn** [comment]
Hi @ChendayUP yes this library currently targetting iOS 9+. 
Realistically, I will likely bump that to iOS 10+ shortly (~3 months) after iOS 11 comes out, as the general rule I follow for iOS is to support only the last two releases (so as to take advantage of the great newness). If there's a specific use case for iOS 8, though, I'm more than happy to accept a PR for support. If it breaks anything and/or changes fundamental library design, though, I'd likely only accept it as a separate branch you'd still be able to use, though. 
Please reopen this issue if you have any further questions, but as the podspec states this pod currently only supports iOS 9+. Thanks!
