### ISSUE TITLE
Failed to build Pod using new XCode 9 build system

### ISSUE THREAD

**Issue by ValeriyMaliuk** [ActionKit/ActionKit#31]
```
error: unable to build node: '/Users/mitusha/Library/Developer/Xcode/DerivedData/Seequre-gbaihqjeapccgubvlatqubgeiupx/Build/Products/Debug-
iphonesimulator/ActionKit/ActionKit.framework/Info.plist' (node is produced by multiple commands; 
e.g., '28cc143554b842798526fb3db67e8978c7a51e241ce7f43b101647fcd45d59e0:CopyPlistFile 
/Users/mitusha/Library/Developer/Xcode/DerivedData/Seequre-
gbaihqjeapccgubvlatqubgeiupx/Build/Products/Debug-iphonesimulator
/ActionKit/ActionKit.framework/Info.plist /Users/mitusha/unicreo/seequre-ios/Pods/ActionKit/ActionKit/Info.plist' and 
'28cc143554b842798526fb3db67e8978c7a51e241ce7f43b101647fcd45d59e0:ProcessInfoPlistFile 
/Users/mitusha/Library/Developer/Xcode/DerivedData/Seequre-gbaihqjeapccgubvlatqubgeiupx/Build/Products/Debug-
iphonesimulator
/ActionKit/ActionKit.framework/Info.plist /Users/mitusha/unicreo/seequre-
ios/Pods/Target Support Files/ActionKit/Info.plist')
```
This could be easily resolved by manual deleting of duplicated info.plist in pod folder.

Version 2.2.0

Could you please fix it?

**Comment by coolbnjmn** [comment]
Hi @ValeriyMaliuk!

Not sure what you mean by:
> This could be easily resolved by manual deleting of duplicated info.plist in pod folder.

This is true for you, locally, but is not the case of the cocoapod itself. 

>in pod folder
There is no "pod folder" inside the `ActionKit` pod, this is something that is generated for you locally when you run `pod install`, this is the beauty of Cocoapods at work! From the log you sent, however, it seems like a `DerivedData` corruption of some kind. 

I'd recommend going to your Derived Data and wiping it (it is rebuilt by Xcode "for free" -- the next build will just take a bit longer). This should resolve this, and if it doesn't I'd do that again but also do a `pod install` after, and THEN open Xcode.

I hope this resolves your issue, please let me know if it doesn't!
- Benjamin

**Comment by phucnm** [comment]
@coolbnjmn : I'm having the same issue while I can build successfully with the legacy build system. (Cleaned build folder before build already)

**Comment by coolbnjmn** [comment]
@phucnm the screenshot helped a lot! I think I determined the issue: the Info.plist file was correctly only committed once, but since it was incorrectly still showing version 1.1.0 (instead of 2.2.0 at the time of this issue), the pod install operation generated a new one, causing the issue.

I've amended the file and this should no longer happen. Check out version 2.3.0 and let me know if that fixes this issue for you.

Please re-open this issue or open a new one either @phucnm or @ValeriyMaliuk if this is not it. I want to thank both of you for using ActionKit and reporting this issue, I hope you have a great day!
- Benjamin

**Comment by phucnm** [comment]
Hi @coolbnjmn , thanks for quick fix on this minor issue. 
This is not a problem to me but there still error when building with new build system with ActionKit 2.3.0, new users with less experience might be frustrated with it.
<img width="979" alt="screen shot 2017-11-29 at 11 05 30 am" src="https://user-images.githubusercontent.com/4024142/33357599-925b08d8-d4f5-11e7-97ea-a4a51d719325.png">
Could you check again ?
Have a nice day!

**Comment by coolbnjmn** [comment]
@phucnm could you elaborate on this a bit more? I'm not seeing what you're seeing as an error in the screenshot you just provided. I'm probably missing something obvious you're trying to report, but I'm missing it so if you could help clarify that for me I'll get it fixed!

Thanks :)
- Benjamin

**Comment by phucnm** [comment]
<img width="1440" alt="screen shot 2017-11-29 at 8 54 45 pm" src="https://user-images.githubusercontent.com/4024142/33378516-a2390e2e-d547-11e7-9366-3ea398141083.png">

**Comment by coolbnjmn** [comment]
@phucnm I think I'm being thick here somewhere and I still don't see it. I did exactly those steps before my first reply, and was able to build my demo project no problem. Which version of cocoapods are you using? and which version of Xcode, just so we're on the exact same page?

Thanks again for your help on this,
- Benjamin

**Comment by phucnm** [comment]
Well, pod version: 1.3.1
Xcode version: Version 9.1 (9B55)
ActionKit: 2.3.0

**Comment by coolbnjmn** [comment]
Hmm, yea I'm using the same setup. Have you deleted your derived data folder recently? It's in that path that it's saying there's a conflict, could you delete it and rebuild?

Derived data is under `~/Library/Developer/Xcode/DerivedData`

**Comment by phucnm** [comment]
Did you build with New Build System ? :D. I have no extra idea why :D

**Comment by coolbnjmn** [comment]
@phucnm oh my, it was something super simple -- I didn't opt in my test project, good catch! 
You mentioned: 
> This is not a problem to me but there still error when building with new build system with ActionKit 2.3.0, new users with less experience might be frustrated with it.

How did you resolve this for yourself locally? This is not something I originally fixed, so this is something new to me. Whatever you did locally would be helpful! 
Thanks :)
- Benjamin

**Comment by phucnm** [comment]
I removed Info.plist from Compile Sources in Build Phases settings. New build system was so strict.

**Comment by coolbnjmn** [comment]
Ah ok, well I'm not sure there's a way to formally fix this, so I'm going to add your advice ^ to the FAQ, as I'm fairly sure this is linked to https://github.com/CocoaPods/CocoaPods/issues/6936 which has not even made a Cocoapods release yet (although a fix was merged, from what I could tell). 

Thanks again for your help @phucnm! 👍

**Comment by phucnm** [comment]
@coolbnjmn Ah I found another way to fix it, you should declare your source files to be .swift files. It might depend on different type of source files but I think it's okay since this repo is written in Swift.

In your ActionKit.podspec, change to this line:
`s.source_files = 'ActionKit/*.swift'`. Dont need to make a PR right ? 😄 

Anw, edit your Info.plist version to match with podspec version

**Comment by coolbnjmn** [comment]
@phucnm no PR needed, `2.3.2` released with this fix, thanks!
