### ISSUE TITLE
Can't load module for 'ActionKit'

### ISSUE THREAD

**Issue by mickychen0524** [ActionKit/ActionKit#32]
import ActionKit gives error 'Cannot load underlying module for 'ActionKit' even pod installed correctly

**Comment by coolbnjmn** [comment]
Hi @mickychen0524, sorry for the delayed reply. 

Can you share a screenshot of the error you're seeing? Can you also share some more details, as I can't quite debug this issue with what you've reported so far. 

Namely, if you could include: Xcode version, Cocoapods version, and Swift version you are using.

Thanks,
- Benjamin

**Comment by coolbnjmn** [comment]
@mickychen0524 just following up, are you still experiencing this issue? If I can't get any more information though I'll close this issue in another week. 

Let me know!
- Benjamin

**Comment by coolbnjmn** [comment]
@mickychen0524 please reopen this with more information if you can still reproduce. I'm going to close this now.
