### ISSUE TITLE
textview support

### ISSUE THREAD

**Issue by choiks14** [ActionKit/ActionKit#33]
plz support uitextview

**Comment by coolbnjmn** [comment]
@choiks14 could you elaborate on what you mean here? I'm not sure what action you'd want `ActionKit` to simplify on a `UITextView`.

Let me know!

**Comment by coolbnjmn** [comment]
@choiks14 still looking for your input here. Happy to try and figure out your use case, but not sure I understand it from your raised issue. If I don't hear back in a couple more days though I will close this issue. 

Thanks for using ActionKit!
- Benjamin

**Comment by coolbnjmn** [comment]
@choiks14 haven't heard from you, please re-open this or another issue if find you can provide more context. Closing this now, though.

Thanks!
- Benjamin
