### ISSUE TITLE
Update to Swift 4.2

### ISSUE THREAD

**Issue by sglushchenko** [ActionKit/ActionKit#34]
Hello,

Are you plan to update ActionKit to Swift 4.2?

**Comment by coolbnjmn** [comment]
Sure! I'm happy to accept a pull request if ou want to take the initiative, otherwise I'll likely have time to get to this later this week :)

**Comment by coolbnjmn** [comment]
Please update to pod version 2.4.0 to get Swift 4.2 support! For all those who don't yet want Swift 4.2, please keep using the version you're on, or there's also the `swift4` branch :)

Thanks for bringing this up @sglushchenko and please do bring up any other issues you might stumble upon!
