### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by joshuawilde** [ActionKit/ActionKit#4]
I'd like to know if this project is MIT licensed or something similar. I'd like to use it in a project but I can't do this if it doesn't have an explicit license.

Thanks.

**Comment by coolbnjmn** [comment]
We currently do not have a license, but feel free to use this project as you please. We will look into what needs to happen to make our project MIT licensed ASAP. 

Thanks

**Comment by austinzheng** [comment]
@coolbnjmn Adding a license is pretty straightforward. All you need to do is to add the MIT license text (http://opensource.org/licenses/MIT) to a 'LICENSE' file in the root and add a note to the Readme that the project is licensed under MIT. It might be a good idea to add something akin to "Licensed under the terms of the MIT license" to the code files as well.

**Comment by coolbnjmn** [comment]
@joshuawilde Added the licensing terms everywhere, it is now under the MIT license. 

Thanks
