### ISSUE TITLE
Making this available on cocoapods

### ISSUE THREAD

**Issue by va3093** [ActionKit/ActionKit#6]
Hey guys, Are you guys thinking about making this available on cocoapods. If not would you accept a pull request from me to make it cocoapods compatible?

**Comment by coolbnjmn** [comment]
We would love to accept a PR to make this cocoa pods compatible and we can
post it to the pods repo.

Thanks

**Comment by va3093** [comment]
Cool. Will hopefully do this soon.

**Comment by ppeelen** [comment]
Done. https://github.com/ActionKit/ActionKit/pull/8

**Comment by coolbnjmn** [comment]
Thanks @ppeelen so much! I've merged it all and pushed it to the cooca pod trunk repo. Should appear at cocoapods.org shortly. 

I'll mark this as resolved.
