### ISSUE TITLE
Adding UIBarButton item support

### ISSUE THREAD

**Issue by va3093** [ActionKit/ActionKit#7]
Are you guys planning to add support to UIBarButtonItem. Would you accept PR if I added support for this?

**Comment by coolbnjmn** [comment]
We would love to accept a PR. This is something we'd love to support but
haven't had time to.

**Comment by kirkvogen** [comment]
I modified some code from [ClosureKit](https://github.com/Reflejo/ClosureKit) to provide **basic** support for UIBarButtonItem. It co-exists with UIClosures and I think it is more-or-less in the spirit of the existing UIControl extension in UIClosures.

It differs from ClosureKit in terms of when the closure is provided. ClosureKit appears to favor programmatic button creation where you provide the closure at construction time. With the code below you can create your button in Interface Builder, expose it as an `IBOutlet`, and then attach the event listener closure.

Here is the code:

```
// UIBarButtonItem+Closure.swift

import Foundation
import UIKit

public typealias CKBarButtonHandler = (sender: UIBarButtonItem) -> Void

private var associatedEventHandle: UInt8 = 0

extension UIBarButtonItem {
    
    private var closuresWrapper: ClosureWrapper? {
        get {
            return objc_getAssociatedObject(self, &associatedEventHandle) as? ClosureWrapper
        }
        
        set {
            objc_setAssociatedObject(self, &associatedEventHandle, newValue,
                objc_AssociationPolicy.OBJC_ASSOCIATION_RETAIN_NONATOMIC)
        }
    }
    
    public func onTouchUpInside(listener: (sender: AnyObject) -> ()) {
        self.closuresWrapper = ClosureWrapper(listener)
        target = self
        action = "handleAction"
    }

    // MARK: Private methods
    @objc
    private func handleAction() {
        self.closuresWrapper?.listener(sender: self)
    }

    // MARK: - Private classes
    private final class ClosureWrapper {
        private var listener: CKBarButtonHandler
        
        init(_ listener: CKBarButtonHandler) {
            self.listener = listener
        }
    }
}
```

**Comment by ManueGE** [comment]
Added a [pull request](https://github.com/ActionKit/ActionKit/pull/17).

**Comment by coolbnjmn** [comment]
Approved it...closing now!
