### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by com314159** [ActionKit/ActionKit#9]
If you don't remove closure manual, it will referenced by ActionKitSingleton.sharedInstance, so the closure will never dealloc even when button is dealloced.  

to solve this problem , you may have to add the closure to UIButton, like BlocksKit(https://github.com/zwaldowski/BlocksKit) did

**Comment by coolbnjmn** [comment]
Sorry for the late response, with the holidays and everything. Anyways, if you would like to submit a PR I'd gladly go over it, but otherwise we probably won't have time to look at this right away. 

Thanks

**Comment by fraserscottmorrison** [comment]
This sound like a pretty serious issue. Im keen to closures for button clicks (for convenience) in a potentially very long message feed. But memory leaks like this can spiral out of control if user keeps infinitely scrolling

**Comment by coolbnjmn** [comment]
I agree @fraserscottmorrison that this is an issue that needs to be addressed. If you have any bandwidth to take a look, it'd be greatly appreciated! If not, I might in a couple weeks.  Thanks!

**Comment by mattijsf** [comment]
I created pr #20 to address this issues

**Comment by coolbnjmn** [comment]
We can maybe have the discussion in the PR itself, but @mattijsf I've commented on your PR asking for some clarification. Would love to get this fixed soon :)

**Comment by com314159** [comment]
Thank you for fix the bug.

**Comment by brodybits** [comment]
What is the status of this?

**Comment by coolbnjmn** [comment]
I have just updated ActionKit with version2, which should handle this memory leak issue! Apologies to everyone for how long that took! If any other issues are found regarding memory leaks in version2, please open a new issue and I will address them there! (quicker than prior versions, for sure).
